# Generated by Django 3.2 on 2023-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articulo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('General', 'General'), ('Diseño Web', 'Diseño Web'), ('Programación', 'Programación')], default='general', max_length=50),
        ),
    ]
